### ISSUE TITLE
Parameterized query

### ISSUE THREAD

**Issue by wonkydonky** [gjhiggins/RDFAlchemy#17]
Is it possible to use this library to create a SPARQL query using parameters? I'm trying to avoid string concatenation for building my queries, but I can't find any library that does this.

For example:

        sparql = SPARQLWrapper ("endpoint")
        sparql.setQuery ('select * where { ?sbj ex:name "' + name + '" }')

should be instead

        sparql = SPARQLWrapper ("endpoint")
        sparql.setQuery ('select * where { ?sbj ex:name $name }', name='Alice')

**Comment by gjhiggins** [comment]
From: the [RDFLib SPARQL intro documentation](https://rdflib.readthedocs.io/en/stable/intro_to_sparql.html#querying-with-sparql):  “Variables can also be pre-bound, using initBindings kwarg can be used to pass in a dict of initial bindings, this is particularly useful for prepared queries, as described below.”
https://rdflib.readthedocs.io/en/stable/intro_to_sparql.html#prepared-queries

**Comment by wonkydonky** [comment]
I've tried that example already, but I can't get `initBindings` to work with a SPARQL endpoint + JSON return format.

**Comment by gjhiggins** [comment]
It's a feature of RDFLib sparql queries of RDFLib graphs: “The method rdflib.plugins.sparql.prepareQuery() takes a query as a string and will return a rdflib.plugins.sparql.sparql.Query object. This can then be passed to the rdflib.graph.Graph.query() method.” As you've discovered, SPARQLWrapper doesn't support this feature but it is possible to use the RDFLib library to create a SPARQL query using parameters.

**Comment by wonkydonky** [comment]
The problem is

- the Graph() object doesn't seem to be able to connect to SPARQL endpoints, only to local, in-memory stores
- SPARQLWrapper only accepts a string, not a Query() object
- the Query() object doesn't have a "convert_to_string_with_bindings()" functionality
